"""Contextual enrichment for document chunks.

Adapted from the Anthropic course context module
(anthropic_course/rag/context/context.py).

Uses an LLM to prepend a short contextual snippet to each chunk,
improving retrieval quality by preserving the chunk's position
within the source document.
"""

from __future__ import annotations


class ContextualEnricher:
    """Enrich text chunks with contextual headers generated by an LLM.

    Args:
        llm: A LangChain-compatible chat model.  When *None*,
            :func:`src.shared.llm.get_llm` is called automatically.
    """

    _PROMPT_TEMPLATE = (
        "Write a short and succinct snippet of text to situate this chunk "
        "within the overall source document for the purposes of improving "
        "search retrieval of the chunk.\n\n"
        "Here is the source document:\n"
        "<document>\n{source}\n</document>\n\n"
        "Here is the chunk to situate:\n"
        "<chunk>\n{chunk}\n</chunk>\n\n"
        "Answer only with the succinct context and nothing else."
    )

    def __init__(self, llm=None) -> None:
        self._llm = llm

    def _get_llm(self):
        if self._llm is not None:
            return self._llm
        from src.shared.llm import get_llm

        self._llm = get_llm(temperature=0.0)
        return self._llm

    def enrich(self, chunk: str, source_text: str) -> str:
        """Return *chunk* prepended with an LLM-generated context line."""
        llm = self._get_llm()
        prompt = self._PROMPT_TEMPLATE.format(source=source_text, chunk=chunk)
        response = llm.invoke([{"role": "user", "content": prompt}])
        context = response.content if hasattr(response, "content") else str(response)
        return context.strip() + "\n" + chunk

    def enrich_batch(
        self,
        chunks: list[str],
        source_text: str,
        context_window: int = 3,
    ) -> list[str]:
        """Enrich multiple chunks from the same source document.

        For large documents, only the first *context_window* chunks
        (as summary context) and the *context_window* chunks immediately
        preceding each chunk are included in the prompt to avoid
        exceeding the model's context window.

        Args:
            chunks: Ordered list of chunks from the source.
            source_text: The full source document text.
            context_window: Number of surrounding chunks to include
                when the source text is large (> 50 000 chars).
        """
        use_windowed = len(source_text) > 50_000

        enriched: list[str] = []
        for i, chunk in enumerate(chunks):
            if use_windowed:
                prefix_chunks = chunks[:context_window]
                start = max(context_window, i - context_window)
                nearby = chunks[start:i]
                context_source = "\n---\n".join(prefix_chunks + nearby)
            else:
                context_source = source_text
            enriched.append(self.enrich(chunk, context_source))
        return enriched
