"""State definition for text2sql agent."""

from __future__ import annotations

from typing import Annotated, Any

from langchain_core.messages import AnyMessage
from langgraph.graph import add_messages
from typing_extensions import TypedDict


class Text2SQLState(TypedDict):
    """State for text2sql agent execution flow."""

    # Input
    prompt: str
    """User's natural language question (e.g., 'Show me top 10 customers by revenue')"""

    # Intermediate steps
    messages: Annotated[list[AnyMessage], add_messages]
    """Full message chain for observability and multi-turn context"""

    catalog: dict[str, Any] | None
    """Database catalog (tables, schemas, relationships) - cached"""

    selected_tables: list[str]
    """LLM-selected tables from initial analysis"""

    expanded_tables: list[str]
    """Tables expanded via graph traversal (includes connectors)"""

    context: str
    """Formatted schema context for SQL generator"""

    generated_query: str | None
    """Initial SQL query generated by LLM"""

    # Feedback loop
    query_iterations: list[dict[str, Any]]
    """List of query attempts with results and errors: [{"query": str, "error": str, "retry": int}]"""

    # Output
    final_query: str | None
    """Final valid SQL query"""

    final_result: dict[str, Any] | None
    """Result from executing final_query"""

    status: str
    """Current status: pending | catalog | selection | expansion | context | generation | iteration | complete"""

    error: str | None
    """Error message if execution failed"""
