id: 1aef3365-ae18-4ee1-a0e7-67c3dc1952cc
name: orca_dolci_evalitahf_negative_inference_2B_all_context
description: "correzione e estensione della ricetta basata su orca e dolci utilizzate\
  \ per prima sperimentazione DPO, questa ricetta non presenta orca long context poiche\
  \ gia inferred per i negatives, sara integrata dopo in una ricetta piu completa\
  \ e bilanciata.\n Gli altri dataset invece sono stati revisionati, per garantire\
  \ anche risposte secche, utili per MMLU bench.\n\nLE DERIVAZIONI DI QUESTA RICETTA\
  \ SONO MOLTEPLICI, MA INSERIAMO SOLO DOLCI-DPO NEGATIVE INFERENCE RELATED DEPENDENCY\
  \ POICHE \xE8 la piu vicina."
scope: sft
tasks:
- information_extraction
- instruction_following
- conversational_dialogue
tags:
- ner
- rag
- instruct
- orca_medium
- orca_short
- inference
- dpo
- negatives
- dolci
- evalitahf
- 2B
derived_from: 9caea437-2753-4992-b91a-5cd267889f00
entries:
- dist_id: 75eef081-e0c0-403a-a88a-6f66791cab1b
  dist_name: velvet2b_ba35217_t0_mapped__query__2_sentence_block_evalita__it
  dist_uri: /nfs/data-download/mapped-data/evalitahf/2_sentence_block_evalita/it
  chat_type: train_dpo
  system_prompt:
      evalita: 'Read carefully the following sentence. Your task is to extract all Nominal
        Entites and categorize them according to the standard (e.g. \"LOC\" for location,
        \"PER\" for person, \"GPE\" for Geopolitical Entity, and so forth). You must
        return your answer as a JSON array with this structure:\n\n[{{ \"entity_text\":
        <entity>, \"type\" : <entity_type>}}]\n\nSentence: {query}'
  replica: 1
  samples: 189
  tokens: 185623
  words: 128459
  validation_error: null
- dist_id: e9131d8d-e884-4376-a953-b60199eb73f6
  dist_name: velvet2b_ba35217_t0_mapped__query__4_sentence_block_evalita__it
  dist_uri: /nfs/data-download/mapped-data/evalitahf/4_sentence_block_evalita/it
  chat_type: train_dpo
  system_prompt:
      evalita: 'Read carefully the following sentence. Your task is to extract all Nominal
        Entites and categorize them according to the standard (e.g. \"LOC\" for location,
        \"PER\" for person, \"GPE\" for Geopolitical Entity, and so forth). You must
        return your answer as a JSON array with this structure:\n\n[{{ \"entity_text\":
        <entity>, \"type\" : <entity_type>}}]\n\nSentence: {query}'
  replica: 1
  samples: 28
  tokens: 11897
  words: 8233
  validation_error: null
- dist_id: cf489087-afac-42f5-a6c1-d6d3a98d7d82
  dist_name: velvet2b_ba35217_t0_mapped__query__6_sentence_block_evalita__it
  dist_uri: /nfs/data-download/mapped-data/evalitahf/6_sentence_block_evalita/it
  chat_type: train_dpo
  system_prompt:
    evalita: 'Read carefully the following sentence. Your task is to extract all Nominal
      Entites and categorize them according to the standard (e.g. \"LOC\" for location,
      \"PER\" for person, \"GPE\" for Geopolitical Entity, and so forth). You must
      return your answer as a JSON array with this structure:\n\n[{{ \"entity_text\":
      <entity>, \"type\" : <entity_type>}}]\n\nSentence: {query}'
  replica: 1
  samples: 4
  tokens: 2729
  words: 1889
  validation_error: null
- dist_id: 4a11319d-1728-4190-b190-87ce3f75b960
  dist_name: velvet2b_ba35217_t0_mapped__query__8_sentence_block_evalita__it
  dist_uri: /nfs/data-download/mapped-data/evalitahf/8_sentence_block_evalita/it
  chat_type: train_dpo
  system_prompt:
    evalita: 'Read carefully the following sentence. Your task is to extract all Nominal
        Entites and categorize them according to the standard (e.g. \"LOC\" for location,
        \"PER\" for person, \"GPE\" for Geopolitical Entity, and so forth). You must
        return your answer as a JSON array with this structure:\n\n[{{ \"entity_text\":
        <entity>, \"type\" : <entity_type>}}]\n\nSentence: {query}'
  replica: 1
  samples: 4
  tokens: 3409
  words: 2359
  validation_error: null
- dist_id: 8497e0a2-4ea5-4f75-af9b-bc5af9387480
  dist_name: velvet2b_ba35217_t0_mapped__query__10_sentence_block_evalita__it
  dist_uri: /nfs/data-download/mapped-data/evalitahf/10_sentence_block_evalita/it
  chat_type: train_dpo
  system_prompt:
    evalita: 'Read carefully the following sentence. Your task is to extract all Nominal
        Entites and categorize them according to the standard (e.g. \"LOC\" for location,
        \"PER\" for person, \"GPE\" for Geopolitical Entity, and so forth). You must
        return your answer as a JSON array with this structure:\n\n[{{ \"entity_text\":
        <entity>, \"type\" : <entity_type>}}]\n\nSentence: {query}'
  replica: 1
  samples: 4
  tokens: 3409
  words: 2359
  validation_error: null
  